"use strict";jQuery('#totop').hide();jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>=100){jQuery('#totop').fadeIn(200);jQuery('#totop').addClass('top-visible')}else{jQuery('#totop').fadeOut(200);jQuery('#totop').removeClass('top-visible')}});jQuery('#totop').on('click',function(){jQuery('body,html').animate({scrollTop:0},500);return!1});var equalheight=function(container){var currentTallest=0,currentRowStart=0,rowDivs=new Array(),$el,topPosition=0;jQuery(container).each(function(){$el=jQuery(this);jQuery($el).outerHeight('auto')
topPostion=$el.position().top;if(currentRowStart!=topPostion){for(currentDiv=0;currentDiv<rowDivs.length;currentDiv++){rowDivs[currentDiv].height(currentTallest)}
rowDivs.length=0;currentRowStart=topPostion;currentTallest=$el.outerHeight();rowDivs.push($el)}else{rowDivs.push($el);currentTallest=(currentTallest<$el.outerHeight())?($el.outerHeight()):(currentTallest)}
for(currentDiv=0;currentDiv<rowDivs.length;currentDiv++){rowDivs[currentDiv].outerHeight(currentTallest)}})}
function ts_sticky(){if(typeof jQuery.fn.stick_in_parent=="function"){var offset_px=0;if(jQuery('body').hasClass('admin-bar')){offset_px=jQuery('#wpadminbar').height()}
var pageWidth=jQuery(window).width();if(parseInt(pageWidth)>parseInt(ts_breakpoint)){jQuery('.ts-stickable-header').stick_in_parent({'parent':'body','spacer':!1,'offset_top':offset_px})}else{jQuery('.ts-stickable-header').trigger("sticky_kit:detach")}}}
function themestek_setCookie(c_name,value,exdays){var now=new Date();var time=now.getTime();time+=(3600*1000)*24;now.setTime(time);var c_value=escape(value)+((exdays==null)?"":"; expires="+now.toGMTString());document.cookie=c_name+"="+c_value}
function themestek_yith_wishlist_func(){jQuery(document).off("click",".add_to_wishlist");jQuery(document).on("click",".add_to_wishlist",function(){var b=yith_wcwl_plugin_ajax_web_url;var opts={add_to_wishlist:jQuery(this).data("product-id"),product_type:jQuery(this).data("product-type"),action:"add_to_wishlist"};mgk_yith_ajax_wish_list(jQuery(this),b,opts);return!1});var mgk_yith_ajax_wish_list=function(obj,ajaxurl,opts){jQuery.ajax({type:"POST",url:ajaxurl,data:"product_id="+opts.add_to_wishlist+"&"+jQuery.param(opts),dataType:'json',success:function(resp){response_result=resp.result,response_message=resp.message;jQuery('body .main-holder div#notification').remove();var ntop=jQuery('#wpadminbar')!==undefined?jQuery('#wpadminbar').height():10;var mainObj=obj.closest('.yith-wcwl-add-to-wishlist');if(response_result=='true'){if(MGK_ADD_TO_WISHLIST_SUCCESS_TEXT!==undefined)
jQuery('<div id="notification" class="row"><div class="success">'+MGK_ADD_TO_WISHLIST_SUCCESS_TEXT+'<img class="close" alt="" src="'+IMAGEURL+'/close.png"></div></div>').prependTo('body .main-holder');jQuery('body .main-holder div#notification').css('top',ntop+'px');jQuery('body .main-holder div#notification > div').fadeIn('show');jQuery('.yith-wcwl-add-button',mainObj).addClass('ts-hide').hide();jQuery('.yith-wcwl-wishlistexistsbrowse',mainObj).addClass('ts-show').show();jQuery('.yith-wcwl-add-button',mainObj).attr('style','display: none !important');jQuery('.yith-wcwl-wishlistexistsbrowse',mainObj).attr('style','display: block !important');jQuery('html,body').animate({scrollTop:0},300)}else if(response_result=='exists'){if(MGK_ADD_TO_WISHLIST_EXISTS_TEXT!==undefined)
jQuery('<div id="notification" class="row"><div class="success">'+MGK_ADD_TO_WISHLIST_EXISTS_TEXT+'<img class="close" alt="" src="'+IMAGEURL+'/close.png"></div></div>').prependTo('body .main-holder');jQuery('body .main-holder div#notification').css('top',ntop+'px');jQuery('body .main-holder div#notification > div').fadeIn('show');jQuery('.yith-wcwl-add-button',mainObj).attr('style','display: none !important');jQuery('.yith-wcwl-wishlistexistsbrowse',mainObj).attr('style','display: show !important');jQuery('html,body').animate({scrollTop:0},300)}
setTimeout(function(){removeNft()},10000)}})};var removeNft=function(){if(jQuery("#notification")!==undefined)
jQuery("#notification").remove()}};function setHeight(column){var maxHeight=0;column=jQuery(column);column.css('height','auto');if(jQuery(window).width()>479){column.each(function(){if(jQuery(this).height()>maxHeight){maxHeight=jQuery(this).height()}});column.height(maxHeight)}}
function themestek_search_form(){if(jQuery('.ts-search-form-wrapper').length>0){jQuery('.ts-search-form-tab > a').on('click',function(e){if(!jQuery(this).parent().hasClass('ts-search-form-tab-disabled')){var mainele=jQuery(this).closest('.ts-search-form-wrapper');var cpt=jQuery(this).data('cpt');jQuery('input[name="post_type"]',mainele).val(cpt);jQuery('form.ts-search-form').submit()}
e.preventDefault()})}}
function themestek_blogmasonry(){if(jQuery().isotope){if(jQuery('#content.themestek-blog-col-page').length>0){jQuery('#content.themestek-blog-col-page').masonry();jQuery('#content.themestek-blog-col-page').isotope({itemSelector:'.post-box',masonry:{},sortBy:'original-order'})}}}
function themestek_stickyFooter(){if(jQuery('body').hasClass('themestek-sticky-footer')){jQuery('div#content-wrapper').css('marginBottom',jQuery('footer#colophon').height())}}
function setEmptySelectBox(element){if(jQuery(element).val()==""){jQuery(element).addClass("empty")}else{jQuery(element).removeClass("empty")}}
function ts_hide_togle_link(){if(jQuery('#navbar div.mega-menu-wrap ul.mega-menu').length>0){jQuery('h3.menu-toggle').css('display','none')}}
function themestek_reset_gmap(){jQuery('.themestek-fbar-box-w > div > aside').each(function(){var mainthis=jQuery(this);jQuery('iframe[src^="https://www.google.com/maps/"], iframe[src^="http://www.google.com/maps/"]',mainthis).each(function(){if(!jQuery(this).hasClass('themestek-set-gmap')){jQuery(this).attr('src',jQuery(this).attr('src')+'');jQuery(this).load(function(){jQuery(this).addClass('themestek-set-gmap').animate({opacity:1},1000)})}})})}
function themestek_hide_gmap(){jQuery('.themestek-fbar-box-w > div > aside').each(function(){var mainthis=jQuery(this);jQuery('iframe[src^="https://www.google.com/maps/"], iframe[src^="http://www.google.com/maps/"]',mainthis).each(function(){if(!jQuery(this).hasClass('themestek-set-gmap')){jQuery(this).css({opacity:0});jQuery(this).css('display','block')}})})}
function themestek_isotope(){jQuery('.themestek-boxes-sortable-yes').each(function(){var gallery_item=jQuery('.themestek-boxes-row-wrapper',this);var filterLinks=jQuery('.ts-sortable-wrapper a',this);gallery_item.isotope({animationEngine:'best-available'})
filterLinks.on('click',function(e){var selector=jQuery(this).attr('data-filter');gallery_item.isotope({filter:selector,itemSelector:'.isotope-item',layoutMode:'fitRows'});filterLinks.removeClass('selected');jQuery('#filter-by li').removeClass('current-cat');jQuery(this).addClass('selected');e.preventDefault()})})};function optico_logMarginPadding(){jQuery('.wpb_column').each(function(){if(jQuery(this).hasClass('ts-left-span')){var margin=jQuery(this).parent().css("padding-left").replace("px","");margin=parseInt(margin);var elewidth=jQuery(this).css("width").replace("px","");elewidth=parseInt(elewidth);var leftsargin=margin+elewidth;var after_inlinecss='';var before_inlinecss='';var randomclass=Math.floor((Math.random()*1000000)+1);randomclass='optico-random-class-'+randomclass;jQuery(this).addClass(randomclass);after_inlinecss+='padding-left: '+leftsargin+'px;';if(jQuery('.vc_column-inner',this).css('background-image')!='none'){var bgimage=jQuery('.vc_column-inner',this).css('background-image');jQuery('.vc_column-inner',this).css('background-image','none','!important');after_inlinecss+='background-image: '+bgimage+';'}
if(jQuery('.vc_column-inner',this).css('background-color')!=''||jQuery('.vc_column-inner',this).css('background-color')!='inherit'){var bgcolor=jQuery('.vc_column-inner',this).css('background-color');before_inlinecss+='background-color: '+bgcolor+';'}
if(after_inlinecss!=''||before_inlinecss!=''){jQuery("head").append('<style>.'+randomclass+':after{'+after_inlinecss+'} .'+randomclass+':before{'+before_inlinecss+'} .ts-left-span .vc_column-inner{background-image:none !important;}</style>')}}})}
function optico_logMarginPadding_right(){jQuery('.wpb_column').each(function(){if(jQuery(this).hasClass('ts-right-span')){var margin=jQuery(this).parent().css("padding-right").replace("px","");margin=parseInt(margin);var elewidth=jQuery(this).css("width").replace("px","");elewidth=parseInt(elewidth);var leftsargin=margin+elewidth;var after_inlinecss='';var before_inlinecss='';var randomclass=Math.floor((Math.random()*1000000)+1);randomclass='optico-random-class-'+randomclass;jQuery(this).addClass(randomclass);after_inlinecss+='padding-right: '+leftsargin+'px;';if(jQuery('.vc_column-inner',this).css('background-image')!='none'){var bgimage=jQuery('.vc_column-inner',this).css('background-image');jQuery('.vc_column-inner',this).css('background-image','none','!important');after_inlinecss+='background-image: '+bgimage+';'}
if(jQuery('.vc_column-inner',this).css('background-color')!=''||jQuery('.vc_column-inner',this).css('background-color')!='inherit'){var bgcolor=jQuery('.vc_column-inner',this).css('background-color');before_inlinecss+='background-color: '+bgcolor+';'}
if(after_inlinecss!=''||before_inlinecss!=''){jQuery("head").append('<style>.'+randomclass+':after{'+after_inlinecss+'} .'+randomclass+':before{'+before_inlinecss+'} .ts-right-span .vc_column-inner{background-image:none !important;}</style>')}}})}
function optico_circle_progressbar(){jQuery('.ts-circle-outer').each(function(){var this_circle=jQuery(this);var emptyFill_val=this_circle.data('emptyfill');var thickness_val=this_circle.data('thickness');var fill_gradient=this_circle.data('gradient');var fill_val=this_circle.data('fill');var startangle_val=(-Math.PI/4*2);if(this_circle.closest('.ts-fid').hasClass('ts-fid-boxstyle-style2')){var startangle_val=(-Math.PI/4*1.7)}
if(fill_gradient!=''){fill_gradient=fill_gradient.split('|');fill_val={gradient:[fill_gradient[0],fill_gradient[1]]}}
if(typeof jQuery.fn.circleProgress=="function"){var digit=this_circle.data('digit');var before=this_circle.data('before');var after=this_circle.data('after');var digit=Number(digit);var short_digit=(digit/100);var size_val=this_circle.data('size');jQuery('.ts-circle',this_circle).circleProgress({value:0,size:size_val,startAngle:startangle_val,thickness:thickness_val,emptyFill:emptyFill_val,fill:fill_val}).on('circle-animation-progress',function(event,progress,stepValue){this_circle.find('.ts-circle-number').html(before+Math.round(stepValue*100)+after)})}
this_circle.waypoint(function(direction){if(!this_circle.hasClass('completed')){if(typeof jQuery.fn.circleProgress=="function"){jQuery('.ts-circle',this_circle).circleProgress({value:short_digit})};this_circle.addClass('completed')}},{offset:'85%'})})}
jQuery(document).ready(function($){"use strict";themestek_search_form();optico_circle_progressbar();jQuery('a[data-rel^="prettyPhoto"]').prettyPhoto();jQuery('a.lightboxvid, .lightboxvid a').prettyPhoto();jQuery('a[rel^="prettyPhoto"]').prettyPhoto();themestek_hide_gmap();jQuery(".themestek-fbar-btn > a.themestek-fbar-btn-link").on('click',function(){if(jQuery(this).closest('.themestek-fbar-main-w').hasClass('themestek-fbar-position-default')){if(jQuery('.themestek-fbar-box-w').css('display')=='none'){jQuery('.ts-fbar-open-icon',this).fadeOut();jQuery('.ts-fbar-close-icon',this).fadeIn();jQuery('.themestek-fbar-box-w').slideDown()}else{jQuery('.ts-fbar-open-icon',this).fadeIn();jQuery('.ts-fbar-close-icon',this).fadeOut();jQuery('.themestek-fbar-box-w').slideUp()}}else{}
return!1});jQuery('.ts-fbar-close, .themestek-fbar-btn > a.themestek-fbar-btn-link, .ts-float-overlay').on('click',function(){jQuery('.themestek-fbar-box-w').toggleClass('animated');jQuery('.ts-float-overlay').toggleClass('animated');jQuery('.themestek-fbar-btn').toggleClass('animated')});jQuery("#site-navigation .nav-menu > li.menu-item-has-children, #site-navigation div.nav-menu > ul > li.page_item_has_children, .ts-mmmenu-override-yes #navbar #site-navigation .mega-menu-wrap .mega-menu.mega-menu-horizontal > li.mega-menu-item-has-children").append("<span class='righticon'><i class='tsicon-fa-plus-square'></i></span>");jQuery('#site-header-menu #site-navigation div.nav-menu > ul > li:has(ul), .ts-mmmenu-override-yes #site-header-menu #site-navigation .mega-menu-wrap > ul > li:has(ul)').append("<span class='righticon'><i class='ts-optico-icon-angle-down'></i></span>");jQuery('.ts-mmmenu-override-yes #site-navigation .mega-menu-wrap > ul > li.menu-item-language ul').addClass("mega-sub-menu");jQuery('.ts-mmmenu-override-yes #navbar #site-navigation .mega-menu-wrap .mega-menu.mega-menu-horizontal > li.menu-item-language > a').show();jQuery('.ts-mmmenu-override-yes #site-navigation .mega-menu-wrap > ul > li.menu-item-language').hover(function(){jQuery('.ts-mmmenu-override-yes #navbar #site-navigation .mega-menu-wrap .mega-menu.mega-menu-horizontal .mega-menu-flyout .mega-sub-menu').css("display","none");jQuery(this).find('ul').show()},function(){jQuery(this).find('ul').hide()});jQuery('.menu li.current-menu-item').parents('li.mega-menu-megamenu').addClass('mega-current-menu-ancestor');if(!jQuery('body').hasClass("ts-header-invert")){jQuery(".nav-menu > li:eq(-2), #site-header-menu #site-navigation div.mega-menu-wrap ul.mega-menu.mega-menu-horizontal > li:eq(-2)").addClass("lastsecond");jQuery(".nav-menu > li:eq(-1), #site-header-menu #site-navigation div.mega-menu-wrap ul.mega-menu.mega-menu-horizontal > li:eq(-1)").addClass("last")}
jQuery('.righticon').on('click',function(){if(jQuery(this).siblings('.sub-menu, .children, .mega-sub-menu').hasClass('open')){jQuery(this).siblings('.sub-menu, .children, .mega-sub-menu').removeClass('open');jQuery('i',jQuery(this)).removeClass('ts-optico-icon-angle-up').addClass('ts-optico-icon-angle-down')}else{jQuery(this).siblings('.sub-menu, .children, .mega-sub-menu').addClass('open');jQuery('i',jQuery(this)).removeClass('ts-optico-icon-angle-down').addClass('ts-optico-icon-angle-up')}
return!1});jQuery("a[data-gal^='prettyPhoto']").prettyPhoto({hook:'data-gal'});jQuery(".themestek-slider-wrapper > div > div > div:contains('Revolution Slider Error')").css("margin-top","0");jQuery('select').select2();themestek_yith_wishlist_func();optico_logMarginPadding();optico_logMarginPadding_right();jQuery('.vc_row-o-equal-height, .ts-equalheightdiv').each(function(){var thisRow=jQuery(this);jQuery('.wpb_column',thisRow).each(function(){var thisColumn=jQuery(this);if(((jQuery('.ts-col-wrapper-bg-layer',thisColumn).length>0&&(jQuery('.ts-col-wrapper-bg-layer',thisColumn).css('background-image')!='none'))||(jQuery('.vc_column-inner',thisColumn).length>0&&(jQuery('.vc_column-inner',thisColumn).css('background-image')!='none')))&&(jQuery('.wpb_wrapper',thisColumn).html().trim()=='')){if(jQuery('.ts-col-wrapper-bg-layer',thisColumn).length>0&&(jQuery('.ts-col-wrapper-bg-layer',thisColumn).css('background-image')!='none')){var bgimage=jQuery('.ts-col-wrapper-bg-layer',thisColumn).css('background-image').replace('url(','');bgimage=bgimage.replace(')','')}else{var bgimage=jQuery('.vc_column-inner',thisColumn).css('background-image').replace('url(','');bgimage=bgimage.replace(')','')}
if(jQuery('.ts-equal-height-image',thisColumn).length==0){jQuery('.vc_column-inner',thisColumn).after('<img src='+bgimage+' class="ts-equal-height-image" />')}
jQuery(thisColumn).addClass('ts-emtydiv')}})});jQuery(".ts-header-search-link a").on('click',function(){jQuery(".ts-search-overlay").addClass('st-show');jQuery("body").addClass('st-prevent-scroll');jQuery(".field.searchform-s").focus();return!1});jQuery(".ts-icon-close").on('click',function(){jQuery(".ts-search-overlay").removeClass('st-show');jQuery("body").removeClass('st-prevent-scroll');return!1});jQuery('.ts-site-searchform').on('click',function(event){event.stopPropagation()});jQuery(".themestek-row-fullwidth-true.full-colum-height-widht > .grid_section > .vc_column_container img.vc_single_image-img").each(function(){var imgsrc=jQuery(this).attr("src");jQuery(this).parent().parent().parent().parent().parent('.vc_column_container').css('background-image','url('+imgsrc+')')});if(typeof jQuery.fn.prettyPhoto=="function"){jQuery('div.gallery a[href*=".jpg"], div.gallery a[href*=".jpeg"], div.gallery a[href*=".png"], div.gallery a[href*=".gif"]').each(function(){if(jQuery(this).attr('target')!='_blank'){jQuery(this).attr('rel','prettyPhoto[wp-gallery]')}});jQuery('.gallery-item a[href*=".jpg"], .gallery-item a[href*=".jpeg"], .gallery-item a[href*=".png"], .gallery-item a[href*=".gif"]').each(function(){if(jQuery(this).attr('target')!='_blank'){jQuery(this).attr('rel','prettyPhoto[coregallery]')}});jQuery('a[href*=".jpg"], a[href*=".jpeg"], a[href*=".png"], a[href*=".gif"]').each(function(){if(jQuery(this).attr('target')!='_blank'&&!jQuery(this).hasClass('prettyphoto')){var attr=$(this).attr('rel');if(typeof attr!==typeof undefined&&attr!==!1&&attr!='prettyPhoto'){jQuery(this).attr('data-rel','prettyPhoto')}}});jQuery('a[data-rel^="prettyPhoto"]').prettyPhoto();jQuery('a.ts_prettyphoto, div.ts_prettyphoto a').prettyPhoto();jQuery('a[rel^="prettyPhoto"]').prettyPhoto();jQuery("a.themestek-open-gallery").on('click',function(){var id=jQuery(this).data('id');var currid=window['api_images_'+id];jQuery.prettyPhoto.open(window['api_images_'+id],window['api_titles_'+id],window['api_desc_'+id])})}
$("[data-appear-animation]").each(function(){var self=$(this);var animation=self.data("appear-animation");var delay=(self.data("appear-animation-delay")?self.data("appear-animation-delay"):0);if($(window).width()>959){self.html('0');self.waypoint(function(direction){if(!self.hasClass('completed')){var from=self.data('from');var to=self.data('to');var interval=self.data('interval');self.numinate({format:'%counter%',from:from,to:to,runningInterval:2000,stepUnit:interval,onComplete:function(elem){self.addClass('completed')}})}},{offset:'85%'})}else{if(animation=='animateWidth'){self.css('width',self.data("width"))}}});if(jQuery('.themestek-testimonial-box').length>0){setHeight('.themestek-testimonial-box.col-lg-6.col-sm-6.col-md-6');setHeight('.themestek-testimonial-box.col-lg-4.col-sm-6.col-md-4');setHeight('.themestek-testimonial-box.col-lg-3.col-sm-6.col-md-3')}
if(jQuery('.ts-stickable-header').length>0){ts_sticky()}
$('#site-navigation a[href="#"]').on('click',function(){return!1});$(".themestek-close-icon").on('click',function(){$("#page").css('padding-top',(parseInt($("#page").css('padding-top'))-parseInt($(".themestek-wbar").height()))+'px');$(".themestek-wbar").slideUp();themestek_setCookie('ts_hidewbar','1',1)});var galleryhtml=jQuery(".gallery-size-full br").each(function(){jQuery(this).remove()});jQuery("a.themestek-open-gallery").on('click',function(){var href=jQuery(this).attr('href');var id=href.replace("#themestek-embed-code-","");var currid=window['api_images_'+id];jQuery.prettyPhoto.open(window['api_images_'+id],window['api_titles_'+id],window['api_desc_'+id])});if(jQuery().isotope){jQuery(window).load(function(){"use strict";themestek_isotope()});jQuery(window).resize(function(){themestek_isotope()})}
$('.themestek-portfolio-likes').on('click',function(e){e.preventDefault();var link=$(this);if(link.hasClass('like-active'))return!1;$(this).html('<i class="fa fa-circle-o-notch fa fa-spin"></i>');var id=$(this).attr('id');$.post(ajaxurl,{action:'themestek-portfolio-likes',likes_id:id},function(data){$('i.fa fa-heart-o',link).removeClass('fa fa-heart-o').addClass('fa fa-heart');link.html(data).addClass('like-active')})});jQuery('footer#colophon').resize(function(){themestek_stickyFooter()});themestek_stickyFooter();equalheight('.ts-equalheightdiv  .wpb_column.vc_column_container');ts_hide_togle_link();jQuery("#ts-header-slider > div > div:contains('Revolution Slider Error')").css("margin","auto");$.fn.smTimeline=function(option,value){jQuery(this).each(function(){var $sm_timeline=jQuery(this);var is_mobile_view=jQuery(window).width()<768;$sm_timeline.find('.timeline-element').each(function(){var $this=jQuery(this);var $timeline_spine=$this.find('.ts-timeline-spine');if(is_mobile_view){$this.addClass('wow fadeInUp');$timeline_spine.attr('style','')}else{if($this.hasClass('left-side')){$this.find('.ts-animation-wrap').addClass('wow fadeInLeft')}else if($this.hasClass('right-side')){$this.find('.ts-animation-wrap').addClass('wow fadeInRight')}
if($this.next().length==0)return;var $next=$this.next();var $next_tl_spine=$next.find('.ts-timeline-spine');if($next.hasClass('ts-date-separator')){$timeline_spine.height($next.offset().top-$timeline_spine.offset().top-5)}else if($next_tl_spine.length){$timeline_spine.height($next_tl_spine.offset().top-$timeline_spine.offset().top-25)}}})})}
jQuery('.themestek-boxes-view-carousel, .themestek-boxes-view-carousel-leftimg, .themestek-boxes-view-carousel-bottomimg').each(function(){var thisElement=jQuery(this);var ts_column=3;var ts_slidestoscroll=3;var ts_slidestoscroll_1200=3;var ts_slidestoscroll_992=3;var ts_slidestoscroll_768=2;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1;if(jQuery(this).data('ts-slidestoscroll')=='1'){var ts_slidestoscroll=1;var ts_slidestoscroll_1200=1;var ts_slidestoscroll_992=1;var ts_slidestoscroll_768=1;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1}
var ts_responsive=[{breakpoint:1200,settings:{slidesToShow:3,slidesToScroll:ts_slidestoscroll_1200}},{breakpoint:768,settings:{slidesToShow:2,slidesToScroll:ts_slidestoscroll_768}},{breakpoint:479,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_479}},{breakpoint:0,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_0}}];if(jQuery(this).hasClass('themestek-boxes-col-three')){ts_column=3;ts_slidestoscroll=3;var ts_slidestoscroll_1200=3;var ts_slidestoscroll_768=2;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1;if(jQuery(this).data('ts-slidestoscroll')=='1'){var ts_slidestoscroll=1;var ts_slidestoscroll_1200=1;var ts_slidestoscroll_768=1;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1}
ts_responsive=[{breakpoint:1200,settings:{slidesToShow:3,slidesToScroll:ts_slidestoscroll_1200,}},{breakpoint:768,settings:{slidesToShow:2,slidesToScroll:ts_slidestoscroll_768}},{breakpoint:479,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_479}},{breakpoint:0,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_0}}]}else if(jQuery(this).hasClass('themestek-boxes-col-one')){ts_column=1;ts_slidestoscroll=1;ts_responsive=[{breakpoint:1200,settings:{slidesToShow:1,slidesToScroll:1,arrows:!0}},{breakpoint:768,settings:{slidesToShow:1,slidesToScroll:1,arrows:!0}},{breakpoint:479,settings:{slidesToShow:1,slidesToScroll:1}},{breakpoint:0,settings:{slidesToShow:1,slidesToScroll:1}}]}else if(jQuery(this).hasClass('themestek-boxes-col-two')){ts_column=2;ts_slidestoscroll=2;var ts_slidestoscroll_1200=2;var ts_slidestoscroll_768=2;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1;if(jQuery(this).data('ts-slidestoscroll')=='1'){var ts_slidestoscroll=1;var ts_slidestoscroll_1200=1;var ts_slidestoscroll_768=1;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1}
ts_responsive=[{breakpoint:1200,settings:{slidesToShow:2,slidesToScroll:ts_slidestoscroll_1200}},{breakpoint:768,settings:{slidesToShow:2,slidesToScroll:ts_slidestoscroll_768}},{breakpoint:479,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_479}},{breakpoint:0,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_0}}]}else if(jQuery(this).hasClass('themestek-boxes-col-four')){ts_column=4;ts_slidestoscroll=4;var ts_slidestoscroll_1200=4;var ts_slidestoscroll_992=3;var ts_slidestoscroll_768=2;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1;if(jQuery(this).data('ts-slidestoscroll')=='1'){var ts_slidestoscroll=1;var ts_slidestoscroll_1200=1;var ts_slidestoscroll_992=1;var ts_slidestoscroll_768=1;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1}
ts_responsive=[{breakpoint:1200,settings:{slidesToShow:4,slidesToScroll:ts_slidestoscroll_1200}},{breakpoint:992,settings:{slidesToShow:3,slidesToScroll:ts_slidestoscroll_992}},{breakpoint:768,settings:{slidesToShow:2,slidesToScroll:ts_slidestoscroll_768}},{breakpoint:479,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_479}},{breakpoint:0,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_0}}]}else if(jQuery(this).hasClass('themestek-boxes-col-five')){ts_column=5;ts_slidestoscroll=5;var ts_slidestoscroll_1200=5;var ts_slidestoscroll_768=3;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1;if(jQuery(this).data('ts-slidestoscroll')=='1'){var ts_slidestoscroll=1;var ts_slidestoscroll_1200=1;var ts_slidestoscroll_768=1;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1}
ts_responsive=[{breakpoint:1200,settings:{slidesToShow:5,slidesToScroll:ts_slidestoscroll_1200}},{breakpoint:768,settings:{slidesToShow:3,slidesToScroll:ts_slidestoscroll_768}},{breakpoint:479,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_479}},{breakpoint:0,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_0}}]}else if(jQuery(this).hasClass('themestek-boxes-col-six')){ts_column=6;ts_slidestoscroll=6;var ts_slidestoscroll_1200=6;var ts_slidestoscroll_768=3;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1;if(jQuery(this).data('ts-slidestoscroll')=='1'){var ts_slidestoscroll=1;var ts_slidestoscroll_1200=1;var ts_slidestoscroll_768=1;var ts_slidestoscroll_479=1;var ts_slidestoscroll_0=1}
ts_responsive=[{breakpoint:1200,settings:{slidesToShow:6,slidesToScroll:ts_slidestoscroll_1200}},{breakpoint:768,settings:{slidesToShow:3,slidesToScroll:ts_slidestoscroll_768}},{breakpoint:479,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_479}},{breakpoint:0,settings:{slidesToShow:1,slidesToScroll:ts_slidestoscroll_0}}]}
var ts_fade=!1;if(jQuery(this).data('ts-effecttype')=='fade'){ts_fade=!0}
var ts_speed=800;if(jQuery.trim(jQuery(this).data('ts-speed'))!=''){ts_speed=jQuery.trim(jQuery(this).data('ts-speed'))}
var ts_autoplay=!1;if(jQuery(this).data('ts-autoplay')=='1'){ts_autoplay=!0}
var ts_autoplayspeed=2000;if(jQuery.trim(jQuery(this).data('ts-autoplayspeed'))!=''){ts_autoplayspeed=jQuery.trim(jQuery(this).data('ts-autoplayspeed'))}
var ts_loop=!1;if(jQuery.trim(jQuery(this).data('ts-loop'))=='1'){ts_loop=!0}
var ts_dots=!1;if(jQuery.trim(jQuery(this).data('ts-dots'))=='1'){ts_dots=!0}
var ts_nav=!1;if(jQuery.trim(jQuery(this).data('ts-nav'))=='1'||jQuery.trim(jQuery(this).data('ts-nav'))=='above'||jQuery.trim(jQuery(this).data('ts-nav'))=='below'){ts_nav=!0}
var ts_centermode=!1;if(jQuery.trim(jQuery(this).data('ts-centermode'))=='1'){ts_centermode=!0}
var ts_pauseonfocus=!1;if(jQuery.trim(jQuery(this).data('ts-pauseonfocus'))=='1'){ts_pauseonfocus=!0}
var ts_pauseonhover=!1;if(jQuery.trim(jQuery(this).data('ts-pauseonhover'))=='1'){ts_pauseonhover=!0}
var ts_rtl=!1;if(jQuery('body').hasClass('rtl')){ts_rtl=!0}
jQuery('.themestek-boxes-row-wrapper > div',this).removeClass(function(index,css){return(css.match(/(^|\s)col-\S+/g)||[]).join(' ')});jQuery('.themestek-boxes-row-wrapper',this).slick({fade:ts_fade,speed:ts_speed,centerMode:ts_centermode,pauseOnFocus:ts_pauseonfocus,pauseOnHover:ts_pauseonhover,slidesToShow:ts_column,slidesToScroll:ts_slidestoscroll,autoplay:ts_autoplay,autoplaySpeed:ts_autoplayspeed,rtl:ts_rtl,dots:ts_dots,pauseOnDotsHover:!1,arrows:ts_nav,adaptiveHeight:!1,infinite:ts_loop,responsive:ts_responsive})});jQuery('.themestek-boxes-row-wrapper',this).on('setPosition',function(event,slick){jQuery(this).find(".ts-flexslider").each(function(){jQuery(this).resize()})});jQuery(".ts-slick-arrow.ts-slick-next",this).on('click',function(){jQuery('.themestek-boxes-row-wrapper',jQuery(this).closest('.themestek-boxes-view-carousel')).slick('slickNext')});jQuery(".ts-slick-arrow.ts-slick-prev",this).on('click',function(){jQuery('.themestek-boxes-row-wrapper',jQuery(this).closest('.themestek-boxes-view-carousel')).slick('slickPrev')});jQuery('.themestek-boxes-view-slickview,.themestek-boxes-view-slickview-leftimg').each(function(){var ts_fade=!1;if(jQuery(this).data('ts-effecttype')=='fade'){ts_fade=!0}
var ts_speed=800;if(jQuery.trim(jQuery(this).data('ts-speed'))!=''){ts_speed=jQuery.trim(jQuery(this).data('ts-speed'))}
var ts_autoplay=!1;if(jQuery(this).data('ts-autoplay')=='1'){ts_autoplay=!0}
var ts_autoplayspeed=2000;if(jQuery.trim(jQuery(this).data('ts-autoplayspeed'))!=''){ts_autoplayspeed=jQuery.trim(jQuery(this).data('ts-autoplayspeed'))}
var ts_loop=!1;if(jQuery.trim(jQuery(this).data('ts-loop'))=='1'){ts_loop=!0}
var ts_dots=!1;if(jQuery.trim(jQuery(this).data('ts-dots'))=='1'){ts_dots=!0}
var ts_nav=!1;if(jQuery.trim(jQuery(this).data('ts-nav'))=='1'){ts_nav=!0}
var testinav=jQuery('.testimonials-nav',this);var testiinfo=jQuery('.testimonials-info',this);var rtloption=!1;if(jQuery('body').hasClass('rtl')){rtloption=!0}
jQuery('.testimonials-info',this).slick({fade:ts_fade,arrows:!0,asNavFor:testinav,adaptiveHeight:!0,speed:ts_speed,autoplay:ts_autoplay,autoplaySpeed:ts_autoplayspeed,infinite:ts_loop,rtl:rtloption});jQuery('.testimonials-nav',this).slick({slidesToShow:1,asNavFor:testiinfo,centerMode:!0,centerPadding:0,focusOnSelect:!0,autoplay:ts_autoplay,autoplaySpeed:ts_autoplayspeed,speed:ts_speed,arrows:ts_nav,dots:ts_dots,variableWidth:!0,infinite:ts_loop,rtl:rtloption})});jQuery('.themestek-boxes-view-slickview-bottomimg').each(function(){var ts_fade=!1;if(jQuery(this).data('ts-effecttype')=='fade'){ts_fade=!0}
var ts_speed=800;if(jQuery.trim(jQuery(this).data('ts-speed'))!=''){ts_speed=jQuery.trim(jQuery(this).data('ts-speed'))}
var ts_autoplay=!1;if(jQuery(this).data('ts-autoplay')=='1'){ts_autoplay=!0}
var ts_autoplayspeed=2000;if(jQuery.trim(jQuery(this).data('ts-autoplayspeed'))!=''){ts_autoplayspeed=jQuery.trim(jQuery(this).data('ts-autoplayspeed'))}
var ts_loop=!1;if(jQuery.trim(jQuery(this).data('ts-loop'))=='1'){ts_loop=!0}
var ts_dots=!1;if(jQuery.trim(jQuery(this).data('ts-dots'))=='1'){ts_dots=!0}
var ts_nav=!1;if(jQuery.trim(jQuery(this).data('ts-nav'))=='1'){ts_nav=!0}
var testinav=jQuery('.testimonials-nav',this);var testiinfo=jQuery('.testimonials-info',this);var rtloption=!1;if(jQuery('body').hasClass('rtl')){rtloption=!0}
jQuery('.testimonials-info',this).slick({fade:ts_fade,arrows:!1,asNavFor:testinav,adaptiveHeight:!0,speed:ts_speed,autoplay:ts_autoplay,autoplaySpeed:ts_autoplayspeed,infinite:ts_loop,rtl:rtloption});jQuery('.testimonials-nav',this).slick({slidesToShow:1,asNavFor:testiinfo,centerMode:!0,centerPadding:0,focusOnSelect:!0,autoplay:ts_autoplay,autoplaySpeed:ts_autoplayspeed,speed:ts_speed,arrows:!0,dots:ts_dots,variableWidth:!0,infinite:ts_loop,rtl:rtloption})});if(jQuery('body').hasClass('themestek-one-page-site')){var x=1;nav=jQuery('.mega-menu-wrap, div.nav-menu');nav.find('a[href="#ts-home"]').parent().addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');nav.find('a').each(function(){if(x!=1){jQuery(this).parent().removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item')}
x=0});var sections=jQuery('.ts-row, #ts-header-slider'),nav=jQuery('.mega-menu-wrap, div.nav-menu'),nav_height=jQuery('#site-navigation').data('sticky-height')-1;jQuery(window).on('scroll',function(){if(jQuery('body').scrollTop()<5){nav.find('a').parent().removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');nav.find('a[href="#ts-home"]').parent().addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item')}
var cur_pos=jQuery(this).scrollTop();sections.each(function(){var top=jQuery(this).offset().top-(nav_height+2),bottom=top+jQuery(this).outerHeight();if(cur_pos>=top&&cur_pos<=bottom){if(typeof jQuery(this)!='undefined'&&typeof jQuery(this).attr('id')!='undefined'&&jQuery(this).attr('id')!=''){var mainThis=jQuery(this);nav.find('a').removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');jQuery(this).addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');var arr=mainThis.attr('id');nav.find('a').parent().removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');nav.find('a').each(function(){var menuAttr=jQuery(this).attr('href').split('#')[1];if(menuAttr==arr){jQuery(this).parent().addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item')}})}}})});nav.find('a').on('click',function(){var $el=jQuery(this),id=$el.attr('href');var arr=id.split('#')[1];jQuery('html, body').animate({scrollTop:jQuery('#'+arr).offset().top-nav_height},500);return!1})}});jQuery(window).load(function(){"use strict";if(jQuery('.ts-flexslider').length>0){jQuery('.ts-flexslider').flexslider({animation:"slide",controlNav:!0,directionNav:!1,start:function(){if(jQuery('.ts-timeline').length>0){jQuery('.ts-timeline').smTimeline()}}})}
function themestek_hide_preloader(){jQuery('.ts-pre-loader-container').fadeOut(1000)}
if(jQuery('.ts-pre-loader-container').length>0){setTimeout(themestek_hide_preloader,100)}
if(jQuery('.ts-timeline').length>0){jQuery('.ts-timeline').smTimeline()}
var $container=jQuery('.portfolio-wrapper');$container.isotope({filter:'*',animationOptions:{duration:750,easing:'linear',queue:!1,}});jQuery('nav.portfolio-sortable-list ul li a').on('click',function(){var selector=jQuery(this).attr('data-filter');$container.isotope({filter:selector,animationOptions:{duration:750,easing:'linear',queue:!1,}});jQuery('nav.portfolio-sortable-list').find('a.selected').removeClass('selected');jQuery(this).addClass('selected');return!1});if(jQuery('.themestek-slider-wrapper .nivoSlider').length>0){jQuery('.themestek-slider-wrapper .nivoSlider').nivoSlider()}
var rtloption=!1;if(jQuery('body').hasClass('rtl')){rtloption=!0}
jQuery('.ts-slick-carousel').slick({autoplay:!0,arrows:!1,dots:!0,rtl:rtloption,});(function(){var nav=jQuery('#site-navigation'),button,menu;if(!nav)
return;button=nav.find('.menu-toggle');if(!button)
return;menu=nav.find('.nav-menu');if(!menu||!menu.children().length){button.hide();return}
jQuery('.menu-toggle').on('click.optico',function(){nav.toggleClass('toggled-on')})})();jQuery('.righticon').each(function(){var mainele=this;if(jQuery(mainele).prev().prev().length>0){if(jQuery(mainele).prev().prev().attr('href')=='#'){jQuery(mainele).prev().prev().on('click',function(){jQuery(mainele).trigger("click")})}}});themestek_blogmasonry();jQuery(".themestek-fbar-content-wrapper").perfectScrollbar({suppressScrollX:!0,includePadding:!0});jQuery(".ts-header-style-classic-vertical .ts-header-block").perfectScrollbar({suppressScrollX:!0,includePadding:!0})});jQuery(window).resize(function(){"use strict";equalheight('.ts-equalheightdiv  .wpb_column.vc_column_container');setTimeout(function(){jQuery('.ts-timeline').smTimeline()},100);if(jQuery('.themestek-testimonial-box').length>0){setHeight('.themestek-testimonial-box.col-lg-4.col-sm-6.col-md-4');setHeight('.themestek-testimonial-box.col-lg-6.col-sm-6.col-md-6');setHeight('.themestek-testimonial-box.col-lg-3.col-sm-6.col-md-3')}
ts_sticky()})